- name: install nginx
  ansible.builtin.package:
    name: nginx
    state: present

- name: start and enable nginx service
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true

# - name: Find all files in directory
#   ansible.builtin.find:
#     paths: /usr/share/nginx/html/
#     file_type: file
#   register: files_to_delete

# - name: Delete files
#   ansible.builtin.file:
#     path: "{{ item.path }}"
#     state: absent
#   loop: "{{ files_to_delete.files }}"

# - name: download package
#   ansible.builtin.get_url:
#     url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
#     dest: /tmp/frontend.zip

# - name: unzip frontend code
#   ansible.builtin.unarchive:
#     src: /tmp/frontend.zip
#     dest: /usr/share/nginx/html
#     remote_src: yes

# - name: import roles from common
#   ansible.builtin.import_role:
#     name: common
#     tasks_from: main

- name: include common role
  include_role:
    name: common
  

- name: copy file
  ansible.builtin.template:
    src: expense.conf.j2
    dest: /etc/nginx/default.d/expense.conf
  notify:
    - Restart nginx
